name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [[ -f requirements.txt ]]; then
          pip install -r requirements.txt
        elif [[ -f pyproject.toml ]]; then
          poetry install
        fi
    - name: Install pytest
      run: |
        if [[ -f tests/ ]]; then
          pip install pytest
        fi
    - name: Run tests
      run: |
        if [[ -f tests/ ]]; then
          pytest
        else
          echo "No tests found, skipping."
        fi
    - name: Run flake8
      run: |
        if [[ -f .flake8 ]]; then
          flake8 .
        fi
    - name: Store artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-results
